/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Pizza;

/**
 *
 * @author unifpvideira
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.controller = new Controller(this);
        this.sabores = new ArrayList<Pizza>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boxTamanho = new javax.swing.JComboBox<>();
        btnFrangoCa = new javax.swing.JButton();
        btnQueijo = new javax.swing.JButton();
        btnAtum = new javax.swing.JButton();
        btnFrangoChe = new javax.swing.JButton();
        btnPort = new javax.swing.JButton();
        btnCala = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        btnPedido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnExibir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnExFrangoCa = new javax.swing.JMenuItem();
        btnExFrangoChe = new javax.swing.JMenuItem();
        btnExQueijo = new javax.swing.JMenuItem();
        btnExPortuguesa = new javax.swing.JMenuItem();
        btnExAtum = new javax.swing.JMenuItem();
        btnExCalabresa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Endereço:");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Tamanho:");

        boxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G" }));
        boxTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTamanhoActionPerformed(evt);
            }
        });

        btnFrangoCa.setText("Frango com Catupiry");
        btnFrangoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrangoCaActionPerformed(evt);
            }
        });

        btnQueijo.setText("Queijo");
        btnQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueijoActionPerformed(evt);
            }
        });

        btnAtum.setText("Atum");
        btnAtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtumActionPerformed(evt);
            }
        });

        btnFrangoChe.setText("Frango com Cheddar");
        btnFrangoChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrangoCheActionPerformed(evt);
            }
        });

        btnPort.setText("Portuguesa");
        btnPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortActionPerformed(evt);
            }
        });

        btnCala.setText("Calabresa");
        btnCala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalaActionPerformed(evt);
            }
        });

        jLabel5.setText("Sabor:");

        jLabel6.setText("Informações sobre o pedido atual:");

        txtPedido.setEditable(false);
        txtPedido.setColumns(20);
        txtPedido.setRows(5);
        txtPedido.setOpaque(false);
        jScrollPane1.setViewportView(txtPedido);

        btnPedido.setText("Concluir Pedido");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        jMenu1.setText("Pedidos");

        btnExibir.setText("Exibir");
        btnExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirActionPerformed(evt);
            }
        });
        jMenu1.add(btnExibir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ingredientes");

        btnExFrangoCa.setText("Frango com Catupiry");
        btnExFrangoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExFrangoCaActionPerformed(evt);
            }
        });
        jMenu2.add(btnExFrangoCa);

        btnExFrangoChe.setText("Frango com Cheddar");
        btnExFrangoChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExFrangoCheActionPerformed(evt);
            }
        });
        jMenu2.add(btnExFrangoChe);

        btnExQueijo.setText("Queijo");
        btnExQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExQueijoActionPerformed(evt);
            }
        });
        jMenu2.add(btnExQueijo);

        btnExPortuguesa.setText("Portuguesa");
        btnExPortuguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExPortuguesaActionPerformed(evt);
            }
        });
        jMenu2.add(btnExPortuguesa);

        btnExAtum.setText("Atum");
        btnExAtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExAtumActionPerformed(evt);
            }
        });
        jMenu2.add(btnExAtum);

        btnExCalabresa.setText("Calabresa");
        btnExCalabresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExCalabresaActionPerformed(evt);
            }
        });
        jMenu2.add(btnExCalabresa);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(txtNome)
                                    .addComponent(txtTelefone)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnQueijo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPort))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnFrangoCa)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnFrangoChe))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAtum)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCala, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138)
                                        .addComponent(jLabel5))))
                            .addComponent(jScrollPane1))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtum, btnCala, btnFrangoCa, btnFrangoChe, btnPort, btnQueijo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrangoCa)
                    .addComponent(btnFrangoChe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQueijo)
                    .addComponent(btnPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtum)
                    .addComponent(btnCala))
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtum, btnCala, btnFrangoCa, btnFrangoChe, btnPort, btnQueijo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtumActionPerformed
        sabores.add(controller.atum());
    }//GEN-LAST:event_btnAtumActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void boxTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTamanhoActionPerformed

    private void btnFrangoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrangoCaActionPerformed
        sabores.add(controller.frangoCatu());
    }//GEN-LAST:event_btnFrangoCaActionPerformed

    private void btnFrangoCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrangoCheActionPerformed
        sabores.add(controller.frangoChe());
    }//GEN-LAST:event_btnFrangoCheActionPerformed

    private void btnQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueijoActionPerformed
        sabores.add(controller.queijo());
    }//GEN-LAST:event_btnQueijoActionPerformed

    private void btnPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortActionPerformed
        sabores.add(controller.portuguesa());
    }//GEN-LAST:event_btnPortActionPerformed

    private void btnCalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalaActionPerformed
        sabores.add(controller.calabresa());
    }//GEN-LAST:event_btnCalaActionPerformed

    private void btnExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirActionPerformed
        controller.exibiPJ();
    }//GEN-LAST:event_btnExibirActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        controller.concluiPedido(sabores);
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnExFrangoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExFrangoCaActionPerformed
        controller.opCatu();
    }//GEN-LAST:event_btnExFrangoCaActionPerformed

    private void btnExFrangoCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExFrangoCheActionPerformed
        controller.opChe();
    }//GEN-LAST:event_btnExFrangoCheActionPerformed

    private void btnExQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExQueijoActionPerformed
        controller.opQueijo();
    }//GEN-LAST:event_btnExQueijoActionPerformed

    private void btnExPortuguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExPortuguesaActionPerformed
        controller.opPortuguesa();
    }//GEN-LAST:event_btnExPortuguesaActionPerformed

    private void btnExAtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExAtumActionPerformed
        controller.opAtum();
    }//GEN-LAST:event_btnExAtumActionPerformed

    private void btnExCalabresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExCalabresaActionPerformed
        controller.opCalabresa();
    }//GEN-LAST:event_btnExCalabresaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    public javax.swing.JTextArea getTxtPedido(){
        return txtPedido;
    }
    public javax.swing.JTextField getNome(){
        return txtNome;
    }
    public javax.swing.JTextField getEndereco(){
        return txtEndereco;
    }
    public javax.swing.JTextField getTel(){
        return txtTelefone;
    }
    public javax.swing.JComboBox<String> getTamanho(){
        return boxTamanho;
    }
    public ArrayList<Pizza> getSabores(){
        return sabores;
    }

    private ArrayList<Pizza> sabores;
    private Controller controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTamanho;
    private javax.swing.JButton btnAtum;
    private javax.swing.JButton btnCala;
    private javax.swing.JMenuItem btnExAtum;
    private javax.swing.JMenuItem btnExCalabresa;
    private javax.swing.JMenuItem btnExFrangoCa;
    private javax.swing.JMenuItem btnExFrangoChe;
    private javax.swing.JMenuItem btnExPortuguesa;
    private javax.swing.JMenuItem btnExQueijo;
    private javax.swing.JMenuItem btnExibir;
    private javax.swing.JButton btnFrangoCa;
    private javax.swing.JButton btnFrangoChe;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnPort;
    private javax.swing.JButton btnQueijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtPedido;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
